version: "3"
services:
  app:
    image: auth-service:latest
    container_name: auth-service
    user: root
    entrypoint: /app/entrypoint.sh
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_service
      DB_HOST: 'postgresauth'
    depends_on:
      - redis
      - postgresauth
    ports:
      - "4000:4000"

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgresauth:
    image: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    # container_name: postgresauth
